services:
  dev:
    build:
      context: ../
      dockerfile: Dockerfile
    image: d2gen
    container_name: d2gen-dev

    stdin_open: true
    tty: true

    volumes:
      - ..:/home/d2gen

    working_dir: /home/d2gen

    entrypoint: "/bin/bash"


